from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "scripts" / "check_active_config_smoke.py"
PROVENANCE_PATH = ROOT / "scripts" / "check_config_provenance.py"


def _load_module(path: Path, name: str):
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ActiveConfigSmokeTests(unittest.TestCase):
    def setUp(self) -> None:
        self.module = _load_module(MODULE_PATH, "check_active_config_smoke")
        self.provenance = _load_module(PROVENANCE_PATH, "check_config_provenance_for_smoke")

    def _write_json(self, path: Path, payload: object) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    def _authority(self, tmp: Path) -> dict[str, object]:
        return {
            "canonical_roots": {"management": str(tmp / "repo")},
            "windows_app_state": {"codex_home": str(tmp / "windows-home" / ".codex")},
            "generation_targets": {
                "global_runtime": {
                    "linux": {
                        "config": str(tmp / "linux-home" / ".codex" / "config.toml"),
                        "agents": str(tmp / "linux-home" / ".codex" / "AGENTS.md"),
                        "hooks_config": str(tmp / "linux-home" / ".codex" / "hooks.json"),
                        "user_override_config": str(tmp / "linux-home" / ".codex" / "user-config.toml"),
                    }
                },
                "global_config": {
                    "required_true_features": [],
                },
            },
        }

    def _write_generated_config(self, path: Path, authority: dict[str, object], body: str, *, authority_path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        header = self.provenance.expected_header(authority, authority_path=authority_path)
        path.write_text(
            "\n".join(
                [
                    "# GENERATED - DO NOT EDIT",
                    "# GENERATED BY Dev-Management",
                    f"# source_authority={header['source_authority']}",
                    f"# source_hash={header['source_hash']}",
                    "# generated_at=2026-04-21T00:00:00+00:00",
                    "# role=generated_mirror",
                    "# read_by_codex=true",
                    "# read_by_renderer=false",
                    "# user_override_source=false",
                    f"# optional_user_override={header['optional_user_override']}",
                    "# manual_edit=forbidden",
                    "",
                    body.rstrip(),
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    def test_good_linux_config_and_absent_windows_policy_surface_pass(self) -> None:
        with tempfile.TemporaryDirectory(dir="/tmp") as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_json(
                tmp / "repo" / "contracts" / "config_provenance_policy.json",
                {"linux_required_true_features": [], "feature_dependency_rules": {"shell_zsh_fork": {"required_when_true": ["zsh_path"], "path_must_be_absolute": True, "path_must_not_start_with": ["/mnt/c"], "path_must_exist": True}}},
            )
            (tmp / "windows-home" / ".codex").mkdir(parents=True, exist_ok=True)
            self._write_generated_config(
                tmp / "linux-home" / ".codex" / "config.toml",
                authority,
                'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n\n[features]\nchronicle = true\n\n[mcp_servers.context7]\nenabled = true\n\n[mcp_servers.serena]\nenabled = true',
                authority_path=authority_path,
            )

            with patch.object(self.provenance, "AUTHORITY_PATH", authority_path):
                report = self.module.evaluate_active_config_smoke(tmp / "repo")

        self.assertEqual(report["status"], "PASS")
        self.assertEqual(report["gate_status"], "PASS")
        self.assertIsNone(report["linux_active_config"]["shell_zsh_fork"])
        self.assertEqual(report["windows_policy_surface_status"], "PASS")

    def test_shell_zsh_fork_without_zsh_path_blocks(self) -> None:
        with tempfile.TemporaryDirectory(dir="/tmp") as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_json(
                tmp / "repo" / "contracts" / "config_provenance_policy.json",
                {"linux_required_true_features": [], "feature_dependency_rules": {"shell_zsh_fork": {"required_when_true": ["zsh_path"], "path_must_be_absolute": True, "path_must_not_start_with": ["/mnt/c"], "path_must_exist": True}}},
            )
            self._write_generated_config(
                tmp / "linux-home" / ".codex" / "config.toml",
                authority,
                'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n\n[features]\nshell_zsh_fork = true\n\n[mcp_servers.context7]\nenabled = true\n\n[mcp_servers.serena]\nenabled = true',
                authority_path=authority_path,
            )

            with patch.object(self.provenance, "AUTHORITY_PATH", authority_path):
                report = self.module.evaluate_active_config_smoke(tmp / "repo")

        self.assertEqual(report["gate_status"], "BLOCKED")
        self.assertIn("zsh_path", " ".join(report["blockers"]))

    def test_shell_zsh_fork_with_valid_zsh_path_passes(self) -> None:
        with tempfile.TemporaryDirectory(dir="/tmp") as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_json(
                tmp / "repo" / "contracts" / "config_provenance_policy.json",
                {"linux_required_true_features": [], "feature_dependency_rules": {"shell_zsh_fork": {"required_when_true": ["zsh_path"], "path_must_be_absolute": True, "path_must_not_start_with": ["/mnt/c"], "path_must_exist": True}}},
            )
            (tmp / "windows-home" / ".codex").mkdir(parents=True, exist_ok=True)
            fake_zsh = tmp / "bin" / "zsh"
            fake_zsh.parent.mkdir(parents=True, exist_ok=True)
            fake_zsh.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            self._write_generated_config(
                tmp / "linux-home" / ".codex" / "config.toml",
                authority,
                f'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\nzsh_path = "{fake_zsh}"\n\n[features]\nshell_zsh_fork = true\n\n[mcp_servers.context7]\nenabled = true\n\n[mcp_servers.serena]\nenabled = true',
                authority_path=authority_path,
            )

            with patch.object(self.provenance, "AUTHORITY_PATH", authority_path):
                report = self.module.evaluate_active_config_smoke(tmp / "repo")

        self.assertEqual(report["status"], "PASS")
        self.assertEqual(report["gate_status"], "PASS")

    def test_windows_policy_file_blocks(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_json(
                tmp / "repo" / "contracts" / "config_provenance_policy.json",
                {"linux_required_true_features": [], "feature_dependency_rules": {"shell_zsh_fork": {"required_when_true": ["zsh_path"], "path_must_be_absolute": True, "path_must_not_start_with": ["/mnt/c"], "path_must_exist": True}}},
            )
            self._write_generated_config(
                tmp / "linux-home" / ".codex" / "config.toml",
                authority,
                'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n\n[features]\nchronicle = true\n\n[mcp_servers.context7]\nenabled = true\n\n[mcp_servers.serena]\nenabled = true',
                authority_path=authority_path,
            )
            windows_config = tmp / "windows-home" / ".codex" / "config.toml"
            windows_config.parent.mkdir(parents=True, exist_ok=True)
            windows_config.write_text('# GENERATED - DO NOT EDIT\napproval_policy = "on-request"\n', encoding="utf-8")

            with patch.object(self.provenance, "AUTHORITY_PATH", authority_path):
                report = self.module.evaluate_active_config_smoke(tmp / "repo")

        self.assertEqual(report["gate_status"], "BLOCKED")
        self.assertEqual(report["windows_policy_surface_status"], "BLOCKED")
        self.assertTrue(report["windows_policy_surface_findings"])


if __name__ == "__main__":
    unittest.main()
