from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "scripts" / "check_config_provenance.py"


def _load_module():
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("check_config_provenance", MODULE_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("failed to load check_config_provenance.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class CheckConfigProvenanceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.module = _load_module()

    def _authority(self, tmp: Path) -> dict[str, object]:
        return {
            "canonical_roots": {"management": str(tmp / "repo")},
            "hardcoding_definition": {"feature_rules": {"forbidden_feature_flags": ["telepathy", "workspace_dependencies"]}},
            "windows_app_state": {"codex_home": str(tmp / "windows-home" / ".codex")},
            "generation_targets": {
                "global_runtime": {
                    "linux": {
                        "config": str(tmp / "linux-config.toml"),
                        "agents": str(tmp / "linux-agents.md"),
                        "hooks_config": str(tmp / "linux-hooks.json"),
                        "user_override_config": str(tmp / "user-config.toml"),
                    },
                }
            },
        }

    def _write_json(self, path: Path, payload: object) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    def _write_policy(self, repo_root: Path) -> None:
        self._write_json(
            repo_root / "contracts" / "config_provenance_policy.json",
            {
                "blocked_active_feature_flags": ["telepathy", "workspace_dependencies"],
                "blocked_generated_config_values": {
                    "approval_policy": ["never"],
                    "sandbox_mode": ["danger-full-access"],
                },
                "linux_required_true_features": [],
            },
        )

    def _write_generated(self, path: Path, authority: dict[str, object], body: str = "") -> None:
        header = self.module.expected_header(authority)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "\n".join([
                "# GENERATED - DO NOT EDIT",
                "# GENERATED BY Dev-Management",
                f"# source_authority={header['source_authority']}",
                f"# source_hash={header['source_hash']}",
                "# generated_at=2026-04-21T00:00:00+00:00",
                "# role=generated_mirror",
                "# read_by_codex=true",
                "# read_by_renderer=false",
                "# user_override_source=false",
                f"# optional_user_override={header['optional_user_override']}",
                "# manual_edit=forbidden",
                "",
                body.rstrip(),
            ]).rstrip() + "\n",
            encoding="utf-8",
        )

    def test_generated_mirror_cannot_be_override_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority["generation_targets"]["global_runtime"]["linux"]["user_override_config"] = str(tmp / "linux-config.toml")
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n[features]\nchronicle = true')
                self._write_generated(tmp / "windows-home" / ".codex" / "config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"')
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertEqual(report["status"], "BLOCKED")
        self.assertIn("linux generated mirror is being used as an override source", report["generated_mirror_contract"]["self_feed_reasons"])

    def test_user_config_only_override_source_passes(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n[features]\nchronicle = true')
                (tmp / "user-config.toml").write_text('approval_policy = "on-request"\n', encoding="utf-8")
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertEqual(report["generated_mirror_contract"]["status"], "PASS")
        self.assertEqual(report["gate_status"], "PASS")
        self.assertEqual(report["status"], "WARN")
        self.assertEqual(report["windows_policy_surface_status"], "PASS")

    def test_telepathy_active_config_is_blocked(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n[features]\ntelepathy = true')
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertEqual(report["status"], "BLOCKED")
        self.assertIn("active telepathy flag detected", report["blocked_reasons"])

    def test_generated_config_never_and_danger_full_access_are_blocked(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "never"\nsandbox_mode = "danger-full-access"')
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertEqual(report["status"], "BLOCKED")
        self.assertIn("generated config still contains approval_policy=never", report["blocked_reasons"])
        self.assertIn("generated config still contains sandbox_mode=danger-full-access", report["blocked_reasons"])

    def test_missing_provenance_marker_blocks_generated_config(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                (tmp / "linux-config.toml").write_text('approval_policy = "on-request"\n', encoding="utf-8")
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertIn(report["generated_headers"][str(tmp / "linux-config.toml")]["status"], {"WARN", "BLOCKED"})

    def test_generic_forbidden_feature_is_blocked(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority["hardcoding_definition"]["feature_rules"]["forbidden_feature_flags"].append("use_agent_identity")
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n[features]\nuse_agent_identity = true')
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertEqual(report["status"], "BLOCKED")
        self.assertIn("active forbidden feature flag detected: use_agent_identity", report["blocked_reasons"])

    def test_unknown_windows_policy_surface_is_warn_only(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            authority = self._authority(tmp)
            authority_path = tmp / "repo" / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(tmp / "repo")
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "windows-home" / ".codex"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"\n[features]\nshell_zsh_fork = true')
                windows_config = tmp / "windows-home" / ".codex" / "config.toml"
                windows_config.parent.mkdir(parents=True, exist_ok=True)
                windows_config.write_text('approval_policy = "on-request"\n', encoding="utf-8")
                report = self.module.evaluate_config_provenance(tmp / "repo")
        self.assertEqual(report["gate_status"], "PASS")
        self.assertEqual(report["status"], "WARN")
        self.assertEqual(report["windows_policy_surface_status"], "WARN")
        self.assertEqual(report["unknown_windows_policy_files_observed"], [str(windows_config)])

    def test_worktree_cannot_become_source_of_truth(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            canonical_root = tmp / "repo-main"
            worktree_root = tmp / "repo-worktree"
            authority = self._authority(tmp)
            authority["authority_root"] = str(canonical_root)
            authority["canonical_roots"] = {"management": str(canonical_root)}
            authority_path = worktree_root / "contracts" / "workspace_authority.json"
            self._write_json(authority_path, authority)
            self._write_policy(canonical_root)
            with patch.object(self.module, "AUTHORITY_PATH", authority_path), patch.object(self.module, "WINDOWS_CODEX_HOME", tmp / "missing-app-state"):
                self._write_generated(tmp / "linux-config.toml", authority, 'approval_policy = "on-request"\nsandbox_mode = "workspace-write"')
                report = self.module.evaluate_config_provenance(worktree_root)
        self.assertEqual(report["status"], "BLOCKED")
        self.assertIn("worktree attempted to use non-canonical authority source", " ".join(report["blocked_reasons"]))


if __name__ == "__main__":
    unittest.main()
