#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
AUTHORITY_PATH = ROOT / "contracts" / "workspace_authority.json"
DEFAULT_OUTPUT = ROOT / "reports" / "canonical-runtime-activation.json"
CONFIG_MARKER_BEGIN = "# BEGIN DEV-MANAGEMENT SSH INCLUDE"
CONFIG_MARKER_END = "# END DEV-MANAGEMENT SSH INCLUDE"
AUTH_KEYS_MARKER_BEGIN = "# BEGIN DEV-MANAGEMENT CANONICAL RUNTIME KEY"
AUTH_KEYS_MARKER_END = "# END DEV-MANAGEMENT CANONICAL RUNTIME KEY"


def home_dir() -> Path:
    return Path.home()


def load_json(path: Path, default: Any | None = None) -> Any:
    if not path.exists():
        return {} if default is None else default
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def status_exit_code(status: str) -> int:
    if status == "PASS":
        return 0
    if status == "WARN":
        return 1
    return 2


def collapse_status(values: list[str]) -> str:
    filtered = [value for value in values if value]
    if any(value == "BLOCKED" for value in filtered):
        return "BLOCKED"
    if any(value == "WARN" for value in filtered):
        return "WARN"
    return "PASS"


def run(argv: list[str]) -> dict[str, Any]:
    try:
        result = subprocess.run(
            argv,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except OSError as exc:
        return {"ok": False, "exit_code": None, "stdout": "", "stderr": str(exc), "argv": argv}
    return {
        "ok": result.returncode == 0,
        "exit_code": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "argv": argv,
    }


def load_authority() -> dict[str, Any]:
    return load_json(AUTHORITY_PATH, default={})


def authority_surface(authority: dict[str, Any]) -> dict[str, Any]:
    return authority.get("canonical_remote_execution_surface", authority.get("canonical_execution_surface", {}))


def ssh_paths() -> dict[str, Path]:
    ssh_root = home_dir() / ".ssh"
    return {
        "ssh_root": ssh_root,
        "config_dir": ssh_root / "config.d",
        "config": ssh_root / "config",
        "snippet": ssh_root / "config.d" / "dev-management.conf",
        "private_key": ssh_root / "devmgmt_wsl_ed25519",
        "public_key": ssh_root / "devmgmt_wsl_ed25519.pub",
        "authorized_keys": ssh_root / "authorized_keys",
    }


def render_snippet(authority: dict[str, Any]) -> str:
    surface = authority_surface(authority)
    user = os.environ.get("USER", "andy4917")
    return (
        "# GENERATED - DO NOT EDIT\n"
        "# generated by Dev-Management\n"
        f"# authority file: {AUTHORITY_PATH}\n"
        "# rollback: remove this file and the matching include block from ~/.ssh/config\n\n"
        f"Host {surface.get('host_alias', 'devmgmt-wsl')}\n"
        "    HostName localhost\n"
        "    Port 22\n"
        f"    User {user}\n"
        "    IdentityFile ~/.ssh/devmgmt_wsl_ed25519\n"
        "    IdentitiesOnly yes\n"
        "    StrictHostKeyChecking accept-new\n"
    )


def render_include_block() -> str:
    return (
        f"{CONFIG_MARKER_BEGIN}\n"
        "Include ~/.ssh/config.d/*.conf\n"
        f"{CONFIG_MARKER_END}\n"
    )


def render_authorized_keys_block(public_key: str) -> str:
    return (
        f"{AUTH_KEYS_MARKER_BEGIN}\n"
        f"{public_key.strip()}\n"
        f"{AUTH_KEYS_MARKER_END}\n"
    )


def backup_path(path: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return path.with_name(f"{path.name}.bak.{timestamp}")


def ensure_mode(path: Path, mode: int, *, apply: bool) -> bool:
    if not path.exists():
        return False
    try:
        current = path.stat().st_mode & 0o777
    except OSError:
        return False
    if current == mode:
        return False
    if apply:
        path.chmod(mode)
    return True


def write_text(path: Path, content: str, *, apply: bool) -> bool:
    changed = not path.exists() or path.read_text(encoding="utf-8") != content
    if changed and apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return changed


def ensure_config_include(config_path: Path, *, apply: bool) -> tuple[bool, list[str]]:
    block = render_include_block()
    backups: list[str] = []
    if not config_path.exists():
        if apply:
            config_path.parent.mkdir(parents=True, exist_ok=True)
            config_path.write_text(block, encoding="utf-8")
        return True, backups

    content = config_path.read_text(encoding="utf-8")
    if CONFIG_MARKER_BEGIN in content and CONFIG_MARKER_END in content:
        return False, backups

    if apply:
        backup = backup_path(config_path)
        shutil.copy2(config_path, backup)
        backups.append(str(backup))
        updated = content
        if updated and not updated.endswith("\n"):
            updated += "\n"
        if updated and not updated.endswith("\n\n"):
            updated += "\n"
        updated += block
        config_path.write_text(updated, encoding="utf-8")
    return True, backups


def fingerprint_for_public_key(public_key_path: Path) -> str:
    if not public_key_path.exists():
        return ""
    result = run(["ssh-keygen", "-lf", str(public_key_path)])
    return str(result["stdout"]).strip() if result["ok"] else ""


def ensure_keypair(private_key: Path, public_key: Path, *, apply: bool, allow_ssh_keygen: bool) -> tuple[bool, list[str], str]:
    planned: list[str] = []
    created = False
    if private_key.exists() and public_key.exists():
        return created, planned, fingerprint_for_public_key(public_key)
    if not allow_ssh_keygen:
        planned.append("ssh key generation is required but --allow-ssh-keygen was not provided")
        return created, planned, ""
    planned.append("generate dedicated localhost SSH keypair for devmgmt-wsl")
    if apply:
        private_key.parent.mkdir(parents=True, exist_ok=True)
        result = run(
            [
                "ssh-keygen",
                "-q",
                "-t",
                "ed25519",
                "-N",
                "",
                "-C",
                "devmgmt-wsl@local",
                "-f",
                str(private_key),
            ]
        )
        if result["ok"]:
            created = True
    return created, planned, fingerprint_for_public_key(public_key)


def ensure_authorized_keys(path: Path, public_key_path: Path, *, apply: bool) -> tuple[bool, bool]:
    if not public_key_path.exists():
        return False, False
    public_key = public_key_path.read_text(encoding="utf-8").strip()
    if not public_key:
        return False, False
    block = render_authorized_keys_block(public_key)
    content = path.read_text(encoding="utf-8") if path.exists() else ""
    if AUTH_KEYS_MARKER_BEGIN in content and AUTH_KEYS_MARKER_END in content:
        return False, True
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        updated = content
        if updated and not updated.endswith("\n"):
            updated += "\n"
        updated += block
        path.write_text(updated, encoding="utf-8")
    return True, False


def ssh_probe(host_alias: str, repo_root: Path) -> dict[str, Any]:
    repo_q = shlex.quote(str(repo_root))
    commands = {
        "hostname": "hostname",
        "repo_root": f"cd {repo_q} && git rev-parse --show-toplevel",
        "command_v_codex": f"cd {repo_q} && command -v codex || true",
        "type_a_codex": f"cd {repo_q} && type -a codex || true",
        "path_entries": "printf '%s\\n' \"$PATH\" | tr ':' '\\n'",
    }
    results: dict[str, Any] = {}
    for key, command in commands.items():
        result = run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=5", host_alias, command])
        results[key] = {
            "ok": bool(result["ok"]),
            "exit_code": result["exit_code"],
            "stdout": str(result["stdout"]).strip(),
            "stderr": str(result["stderr"]).strip(),
        }
    hostname_ok = bool(results["hostname"]["ok"])
    repo_ok = bool(results["repo_root"]["ok"] and results["repo_root"]["stdout"] == str(repo_root))
    status = "PASS" if hostname_ok and repo_ok else "BLOCKED"
    return {
        "status": status,
        "host_alias": host_alias,
        "hostname": results["hostname"]["stdout"],
        "repo_root_ok": repo_ok,
        "results": results,
    }


def activate_runtime(*, apply_user_level: bool, allow_ssh_keygen: bool) -> dict[str, Any]:
    authority = load_authority()
    surface = authority_surface(authority)
    repo_root = Path(str(surface.get("repo_root", ROOT))).expanduser().resolve()
    host_alias = str(surface.get("host_alias", "devmgmt-wsl")).strip() or "devmgmt-wsl"
    paths = ssh_paths()

    actions_planned: list[str] = []
    actions_applied: list[str] = []
    files_touched: list[str] = []
    backups_created: list[str] = []
    warnings: list[str] = []

    actions_planned.append("ensure ~/.ssh exists with user-only permissions")
    if apply_user_level:
        paths["ssh_root"].mkdir(parents=True, exist_ok=True)
    if ensure_mode(paths["ssh_root"], 0o700, apply=apply_user_level):
        if apply_user_level:
            actions_applied.append("normalized ~/.ssh permissions to 700")
            files_touched.append(str(paths["ssh_root"]))

    snippet_changed = write_text(paths["snippet"], render_snippet(authority), apply=apply_user_level)
    if snippet_changed:
        actions_planned.append("write ~/.ssh/config.d/dev-management.conf")
        if apply_user_level:
            actions_applied.append("wrote ~/.ssh/config.d/dev-management.conf")
            files_touched.append(str(paths["snippet"]))
            ensure_mode(paths["config_dir"], 0o700, apply=True)

    include_changed, include_backups = ensure_config_include(paths["config"], apply=apply_user_level)
    backups_created.extend(include_backups)
    if include_changed:
        actions_planned.append("ensure ~/.ssh/config includes ~/.ssh/config.d/*.conf")
        if apply_user_level:
            actions_applied.append("updated ~/.ssh/config include block")
            files_touched.append(str(paths["config"]))

    key_created, key_plans, fingerprint = ensure_keypair(
        paths["private_key"],
        paths["public_key"],
        apply=apply_user_level,
        allow_ssh_keygen=allow_ssh_keygen,
    )
    actions_planned.extend(plan for plan in key_plans if plan not in actions_planned)
    if key_created:
        actions_applied.append("generated dedicated SSH keypair for devmgmt-wsl")
        files_touched.extend([str(paths["private_key"]), str(paths["public_key"])])
    if paths["private_key"].exists():
        if ensure_mode(paths["private_key"], 0o600, apply=apply_user_level) and apply_user_level:
            actions_applied.append("normalized private key permissions to 600")
            files_touched.append(str(paths["private_key"]))
    if paths["public_key"].exists():
        if ensure_mode(paths["public_key"], 0o644, apply=apply_user_level) and apply_user_level:
            actions_applied.append("normalized public key permissions to 644")
            files_touched.append(str(paths["public_key"]))

    auth_changed, auth_present = ensure_authorized_keys(paths["authorized_keys"], paths["public_key"], apply=apply_user_level)
    if auth_changed:
        actions_planned.append("append marker-based public key block to ~/.ssh/authorized_keys")
        if apply_user_level:
            actions_applied.append("updated ~/.ssh/authorized_keys")
            files_touched.append(str(paths["authorized_keys"]))
    if apply_user_level and paths["authorized_keys"].exists():
        if ensure_mode(paths["authorized_keys"], 0o600, apply=True):
            actions_applied.append("normalized authorized_keys permissions to 600")
            files_touched.append(str(paths["authorized_keys"]))
    if not paths["public_key"].exists():
        warnings.append("dedicated public key is not present yet; SSH auth will remain blocked until a keypair exists")

    probe = ssh_probe(host_alias, repo_root)
    if not probe["status"] == "PASS" and not apply_user_level:
        status = "WARN"
    else:
        status = probe["status"]
    if not allow_ssh_keygen and not paths["private_key"].exists():
        status = collapse_status([status, "WARN"])

    return {
        "status": status,
        "apply_user_level": apply_user_level,
        "allow_ssh_keygen": allow_ssh_keygen,
        "actions_planned": actions_planned,
        "actions_applied": actions_applied,
        "files_touched": sorted(set(files_touched)),
        "backups_created": backups_created,
        "key_material": {
            "private_key_path": str(paths["private_key"]),
            "public_key_path": str(paths["public_key"]),
            "private_key_exists": paths["private_key"].exists(),
            "public_key_exists": paths["public_key"].exists(),
            "authorized_keys_path": str(paths["authorized_keys"]),
            "authorized_keys_marker_present": auth_present or auth_changed,
            "public_key_fingerprint": fingerprint,
        },
        "ssh_probe_result": probe,
        "recommended_next_actions": (
            ["re-run activation with --apply-user-level --allow-ssh-keygen"] if not apply_user_level and not paths["private_key"].exists() else
            ["run python3 scripts/check_global_runtime.py --json after SSH activation"] if probe["status"] == "PASS" else
            ["review ~/.ssh/config include, authorized_keys marker, and localhost SSH server logs manually"]
        ),
        "warnings": warnings,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Activate the canonical SSH runtime at the user-account level.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing files.")
    parser.add_argument("--apply-user-level", action="store_true", help="Apply user-level SSH activation changes.")
    parser.add_argument("--allow-ssh-keygen", action="store_true", help="Allow dedicated SSH key generation.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--output-file", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    apply_user_level = bool(args.apply_user_level and not args.dry_run)
    report = activate_runtime(apply_user_level=apply_user_level, allow_ssh_keygen=bool(args.allow_ssh_keygen))
    if args.output_file:
        save_json(Path(args.output_file).expanduser().resolve(), report)
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(f"canonical runtime activation status: {report['status']}")
        print(f"- host alias: {report['ssh_probe_result']['host_alias']}")
        print(f"- repo probe ok: {report['ssh_probe_result']['repo_root_ok']}")
        print(f"- private key exists: {report['key_material']['private_key_exists']}")
        print(f"- public key exists: {report['key_material']['public_key_exists']}")
    return status_exit_code(report["status"])


if __name__ == "__main__":
    raise SystemExit(main())
