#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from render_codex_runtime import render_agents, render_hooks, user_override_config_paths


ROOT = Path(__file__).resolve().parents[1]
AUTHORITY_PATH = ROOT / "contracts" / "workspace_authority.json"
DEFAULT_OUTPUT_PATH = ROOT / "reports" / "config-provenance.unified-phase.json"
WINDOWS_CODEX_HOME = Path("/mnt/c/Users/anise/.codex")


def load_json(path: Path, default: Any | None = None) -> Any:
    if not path.exists():
        return {} if default is None else default
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def collapse_status(values: list[str]) -> str:
    items = [value for value in values if value]
    if any(value == "BLOCKED" for value in items):
        return "BLOCKED"
    if any(value == "WARN" for value in items):
        return "WARN"
    return "PASS"


def status_exit_code(status: str) -> int:
    if status == "PASS":
        return 0
    if status == "WARN":
        return 1
    return 2


def load_authority(repo_root: str | Path | None = None) -> dict[str, Any]:
    authority_path = AUTHORITY_PATH if repo_root is None else Path(repo_root).expanduser().resolve() / "contracts" / "workspace_authority.json"
    return load_json(authority_path, default={})


def authority_hash() -> str:
    return hashlib.sha256(AUTHORITY_PATH.read_bytes()).hexdigest()


def expected_header(authority: dict[str, Any]) -> dict[str, str]:
    runtime = authority.get("generation_targets", {}).get("global_runtime", {})
    override_path = str(runtime.get("linux", {}).get("user_override_config", Path.home() / ".codex" / "user-config.toml"))
    return {
        "marker": "# GENERATED BY Dev-Management",
        "source_authority": str(AUTHORITY_PATH),
        "source_hash": authority_hash(),
        "role": "generated_mirror",
        "optional_user_override": override_path,
    }


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def load_toml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("rb") as handle:
        return tomllib.load(handle)


def runtime_paths(authority: dict[str, Any]) -> dict[str, Path]:
    runtime = authority.get("generation_targets", {}).get("global_runtime", {})
    linux = runtime.get("linux", {})
    windows = runtime.get("windows_mirror", {})
    return {
        "linux_config": Path(str(linux.get("config", Path.home() / ".codex" / "config.toml"))).expanduser().resolve(),
        "linux_agents": Path(str(linux.get("agents", Path.home() / ".codex" / "AGENTS.md"))).expanduser().resolve(),
        "linux_hooks": Path(str(linux.get("hooks_config", Path.home() / ".codex" / "hooks.json"))).expanduser().resolve(),
        "linux_user_override": Path(str(linux.get("user_override_config", Path.home() / ".codex" / "user-config.toml"))).expanduser().resolve(),
        "windows_config": Path(str(windows.get("config", "/mnt/c/Users/anise/.codex/config.toml"))).expanduser().resolve(),
        "windows_agents": Path(str(windows.get("agents", "/mnt/c/Users/anise/.codex/AGENTS.md"))).expanduser().resolve(),
        "windows_hooks": Path(str(windows.get("hooks_config", "/mnt/c/Users/anise/.codex/hooks.json"))).expanduser().resolve(),
    }


def classify_path(path: Path, authority: dict[str, Any], paths: dict[str, Path]) -> str:
    resolved = path.expanduser().resolve()
    if resolved == AUTHORITY_PATH.resolve() or resolved.parent == AUTHORITY_PATH.parent.resolve():
        return "source_of_truth"
    if resolved == paths["linux_user_override"]:
        return "optional_user_override_source"
    if resolved in {paths["linux_config"], paths["windows_config"], paths["linux_agents"], paths["windows_agents"], paths["linux_hooks"], paths["windows_hooks"]}:
        return "generated_mirror"
    if str(resolved).startswith(str(WINDOWS_CODEX_HOME)):
        return "app_state"
    return "unknown"


def header_status(path: Path, authority: dict[str, Any]) -> dict[str, Any]:
    paths = runtime_paths(authority)
    if path.name == "AGENTS.md":
        text = read_text(path)
        checks = {
            "generated_banner": text.startswith("GENERATED - DO NOT EDIT"),
            "authority_file_line": f"- Authority file: `{AUTHORITY_PATH}`" in text,
            "outputs_only_line": "Generated config mirrors are outputs only." in text,
            "user_override_line": "Optional user override source is /home/andy4917/.codex/user-config.toml only." in text,
        }
        if not path.exists():
            return {"status": "WARN", "exists": False, "checks": checks, "reasons": ["generated AGENTS mirror is missing"]}
        expected = render_agents(authority, windows=path.resolve() == paths["windows_agents"])
        reasons = [f"missing AGENTS provenance field: {key}" for key, ok in checks.items() if not ok]
        if text != expected:
            reasons.append("generated AGENTS mirror payload no longer matches the current authority render")
        return {"status": "WARN" if reasons else "PASS", "exists": True, "checks": checks, "reasons": reasons}
    if path.name == "hooks.json":
        expected = render_hooks(authority, windows=path.resolve() == paths["windows_hooks"])
        if expected is None:
            return {"status": "PASS", "exists": path.exists(), "checks": {"expected_generation": False}, "reasons": []}
        if not path.exists():
            return {"status": "WARN", "exists": False, "checks": {"expected_generation": True}, "reasons": ["generated hooks mirror is missing"]}
        text = read_text(path)
        reasons = [] if text == expected else ["generated hooks mirror payload no longer matches the current authority render"]
        return {
            "status": "WARN" if reasons else "PASS",
            "exists": True,
            "checks": {"expected_generation": True, "matches_render": not reasons},
            "reasons": reasons,
        }
    text = read_text(path)
    expected = expected_header(authority)
    lines = text.splitlines()[:12]
    checks = {
        "marker": expected["marker"] in text,
        "source_authority": any(line == f"# source_authority={expected['source_authority']}" for line in lines),
        "source_hash": any(line == f"# source_hash={expected['source_hash']}" for line in lines),
        "role": any(line == "# role=generated_mirror" for line in lines),
        "read_by_renderer": any(line == "# read_by_renderer=false" for line in lines),
        "user_override_source": any(line == "# user_override_source=false" for line in lines),
        "optional_user_override": any(line == f"# optional_user_override={expected['optional_user_override']}" for line in lines),
    }
    if not path.exists():
        return {"status": "WARN", "exists": False, "checks": checks, "reasons": ["generated mirror is missing"]}
    reasons = [f"missing provenance field: {key}" for key, ok in checks.items() if not ok]
    status = "PASS" if not reasons else "BLOCKED" if path.name == "config.toml" else "WARN"
    return {"status": status, "exists": True, "checks": checks, "reasons": reasons}


def config_policy_findings(path: Path, authority: dict[str, Any], classification: str) -> dict[str, Any]:
    payload = load_toml(path)
    features = payload.get("features", {}) if isinstance(payload, dict) else {}
    forbidden_features = set(authority.get("hardcoding_definition", {}).get("feature_rules", {}).get("forbidden_feature_flags", []))
    active_forbidden = sorted(str(feature) for feature, enabled in features.items() if enabled and str(feature) in forbidden_features)
    reasons: list[str] = []
    if "telepathy" in active_forbidden:
        reasons.append("active telepathy flag detected")
    if "workspace_dependencies" in active_forbidden:
        reasons.append("active workspace_dependencies flag detected without explicit authority re-authorization")
    for feature in active_forbidden:
        if feature in {"telepathy", "workspace_dependencies"}:
            continue
        reasons.append(f"active forbidden feature flag detected: {feature}")
    if classification == "generated_mirror" and str(payload.get("approval_policy", "")).strip() == "never":
        reasons.append("generated config still contains approval_policy=never")
    if classification == "generated_mirror" and str(payload.get("sandbox_mode", "")).strip() == "danger-full-access":
        reasons.append("generated config still contains sandbox_mode=danger-full-access")
    return {"status": "BLOCKED" if reasons else "PASS", "blocked_reasons": reasons, "features": features, "approval_policy": str(payload.get("approval_policy", "")), "sandbox_mode": str(payload.get("sandbox_mode", ""))}


def evaluate_config_provenance(repo_root: str | Path | None = None) -> dict[str, Any]:
    authority = load_authority(repo_root)
    paths = runtime_paths(authority)
    override_source_paths = [str(item) for item in user_override_config_paths(authority)]
    mirrors = [paths["linux_config"], paths["windows_config"], paths["linux_agents"], paths["windows_agents"], paths["linux_hooks"], paths["windows_hooks"]]
    classifications = {str(path): classify_path(path, authority, paths) for path in [*mirrors, paths["linux_user_override"], AUTHORITY_PATH]}
    self_feed_reasons: list[str] = []
    if str(paths["linux_config"]) in override_source_paths:
        self_feed_reasons.append("linux generated mirror is being used as an override source")
    if str(paths["windows_config"]) in override_source_paths:
        self_feed_reasons.append("windows generated mirror is being used as an override source")
    if any(path != str(paths["linux_user_override"]) for path in override_source_paths):
        self_feed_reasons.append("optional user override source drifted away from /home/andy4917/.codex/user-config.toml")
    generated_headers = {str(path): header_status(path, authority) for path in mirrors}
    active_config_findings = {str(path): config_policy_findings(path, authority, classifications[str(path)]) for path in [paths["linux_config"], paths["windows_config"], paths["linux_user_override"]]}
    blocked_reasons = list(self_feed_reasons)
    blocked_reasons.extend(reason for payload in active_config_findings.values() for reason in payload.get("blocked_reasons", []))
    blocked_reasons.extend(f"{path_text}: {reason}" for path_text, payload in generated_headers.items() if payload["status"] == "BLOCKED" for reason in payload.get("reasons", []))
    warnings = ["Windows Codex app state exists as evidence only and must not be treated as authority"] if WINDOWS_CODEX_HOME.exists() else []
    status = collapse_status(["BLOCKED" if blocked_reasons else "", "WARN" if warnings else ""])
    return {
        "status": status,
        "gate_status": "BLOCKED" if blocked_reasons else "PASS",
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "authority_path": str(AUTHORITY_PATH),
        "authority_hash": authority_hash(),
        "allowed_optional_user_override_source": str(paths["linux_user_override"]),
        "override_source_paths": override_source_paths,
        "generated_mirror_contract": {"status": "BLOCKED" if self_feed_reasons else "PASS", "self_feed_reasons": self_feed_reasons, "mirrors_are_outputs_only": True},
        "classifications": classifications,
        "generated_headers": generated_headers,
        "active_config_findings": active_config_findings,
        "app_state_surface": {"status": "WARN" if WINDOWS_CODEX_HOME.exists() else "PASS", "path": str(WINDOWS_CODEX_HOME), "classification": "app_state"},
        "blocked_reasons": blocked_reasons,
        "warnings": warnings,
    }


def render_markdown(report: dict[str, Any]) -> str:
    lines = ["# Config Provenance", "", f"- Status: {report['status']}", f"- Allowed optional user override: {report['allowed_optional_user_override_source']}", f"- Override sources: {', '.join(report['override_source_paths']) or '(none)'}"]
    if report.get("blocked_reasons"):
        lines.extend(["", "## Blocked Reasons"])
        lines.extend(f"- {item}" for item in report["blocked_reasons"])
    if report.get("warnings"):
        lines.extend(["", "## Warnings"])
        lines.extend(f"- {item}" for item in report["warnings"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Check Codex config provenance, generated mirror contract, and stale active flags.")
    parser.add_argument("--repo-root", default=str(ROOT))
    parser.add_argument("--output-file", default=str(DEFAULT_OUTPUT_PATH))
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    report = evaluate_config_provenance(args.repo_root)
    output_path = Path(args.output_file).expanduser().resolve()
    save_json(output_path, report)
    output_path.with_suffix(".md").write_text(render_markdown(report), encoding="utf-8")
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(render_markdown(report), end="")
    return status_exit_code(report["status"])


if __name__ == "__main__":
    raise SystemExit(main())
