#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from devmgmt_runtime.authority import authority_path_for, canonical_authority_path, canonical_repo_root, load_authority
from devmgmt_runtime.path_authority import load_path_policy, windows_codex_home
from devmgmt_runtime.paths import runtime_paths
from devmgmt_runtime.reports import load_json, save_json, write_markdown
from devmgmt_runtime.status import collapse_status, status_exit_code
from devmgmt_runtime.windows_policy import windows_policy_surface_report


AUTHORITY_PATH = ROOT / "contracts" / "workspace_authority.json"
DEFAULT_OUTPUT_PATH = ROOT / "reports" / "config-provenance.final.json"
POLICY_PATH = ROOT / "contracts" / "config_provenance_policy.json"
WINDOWS_CODEX_HOME = windows_codex_home(load_path_policy())


def render_agents(_authority: dict[str, Any], *, windows: bool) -> str:
    return ""


def render_hooks(_authority: dict[str, Any], *, windows: bool) -> str | None:
    return None


def load_policy(repo_root: str | Path | None = None) -> dict[str, Any]:
    root = Path(repo_root).expanduser().resolve() if repo_root else ROOT
    path = root / "contracts" / "config_provenance_policy.json"
    if not path.exists():
        if repo_root is not None and root != ROOT:
            return {}
        path = POLICY_PATH
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def authority_hash(path: Path | None = None) -> str:
    target = path or AUTHORITY_PATH
    if not target.exists():
        return ""
    return hashlib.sha256(target.read_bytes()).hexdigest()


def expected_header(
    authority: dict[str, Any],
    authority_path: Path | None = None,
    policy: dict[str, Any] | None = None,
) -> dict[str, str]:
    authority_path = authority_path or AUTHORITY_PATH
    policy = policy or {}
    paths = runtime_paths(authority)
    return {
        "marker": "# GENERATED BY Dev-Management",
        "source_authority": str(authority_path),
        "source_hash": authority_hash(authority_path),
        "role": str(policy.get("generated_mirror_contract", {}).get("role", "generated_mirror")),
        "optional_user_override": str(paths["windows_user_override"]),
    }


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def load_toml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("rb") as handle:
        return tomllib.load(handle)


def required_true_features(policy: dict[str, Any], authority: dict[str, Any]) -> set[str]:
    from_policy = {str(item).strip() for item in policy.get("linux_required_true_features", []) if str(item).strip()}
    if from_policy:
        return from_policy
    cfg = authority.get("generation_targets", {}).get("global_config", {})
    return {str(item).strip() for item in cfg.get("required_true_features", []) if str(item).strip()}


def shell_zsh_fork_dependency_reasons(payload: dict[str, Any], policy: dict[str, Any]) -> list[str]:
    features = payload.get("features", {}) if isinstance(payload.get("features"), dict) else {}
    if features.get("shell_zsh_fork") is not True:
        return []
    rules = policy.get("feature_dependency_rules", {}).get("shell_zsh_fork", {})
    required_when_true = {str(item).strip() for item in rules.get("required_when_true", []) if str(item).strip()}
    zsh_path = str(payload.get("zsh_path", "")).strip()
    reasons: list[str] = []
    if "zsh_path" in required_when_true and not zsh_path:
        reasons.append("active shell_zsh_fork requires zsh_path to be configured")
        return reasons
    if rules.get("path_must_be_absolute") and (not zsh_path or not Path(zsh_path).is_absolute()):
        reasons.append("active shell_zsh_fork requires zsh_path to be an absolute Linux path")
    blocked_prefixes = tuple(str(item) for item in rules.get("path_must_not_start_with", []) if str(item))
    if zsh_path and blocked_prefixes and zsh_path.startswith(blocked_prefixes):
        reasons.append("active shell_zsh_fork cannot use a legacy Linux or mounted path")
    if zsh_path and rules.get("path_must_exist") and not Path(zsh_path).exists():
        reasons.append("active shell_zsh_fork requires zsh_path to exist on the Linux runtime")
    return reasons


def generated_header_present(path: Path) -> bool:
    text = read_text(path)
    return text.startswith("# GENERATED - DO NOT EDIT") or text.startswith("GENERATED - DO NOT EDIT")


def windows_policy_paths(paths: dict[str, Path]) -> list[Path]:
    return [
        paths["observed_windows_policy_config"],
        paths["observed_windows_policy_agents"],
        paths["observed_windows_policy_hooks"],
        paths["observed_windows_policy_skills"],
    ]


def classify_path(path: Path, authority_path: Path, paths: dict[str, Path]) -> str:
    resolved = path.expanduser().resolve()
    if resolved == authority_path.resolve() or resolved.parent == authority_path.parent.resolve():
        return "source_of_truth"
    if resolved in {paths["windows_user_override"], paths["linux_user_override"]}:
        return "optional_user_override_source"
    if resolved in {paths["linux_config"], paths["linux_agents"], paths["linux_hooks"]}:
        return "generated_mirror"
    if resolved in {item.resolve() for item in windows_policy_paths(paths)}:
        return "windows_policy_surface"
    if str(resolved).startswith(str(WINDOWS_CODEX_HOME)):
        return "app_state"
    return "unknown"


def header_status(path: Path, authority: dict[str, Any], authority_path: Path, policy: dict[str, Any]) -> dict[str, Any]:
    paths = runtime_paths(authority)
    if path.name == "AGENTS.md":
        text = read_text(path)
        authority_line = f"- Authority file: {chr(96)}{authority_path}{chr(96)}"
        override_line = f"Optional user override source is `{paths['linux_user_override']}` only."
        checks = {
            "generated_banner": text.startswith("GENERATED - DO NOT EDIT"),
            "authority_file_line": authority_line in text,
            "outputs_only_line": "Linux generated runtime files are outputs only." in text,
            "user_override_line": override_line in text,
        }
        if not path.exists():
            return {"status": "WARN", "exists": False, "checks": checks, "reasons": ["generated AGENTS mirror is missing"]}
        expected = render_agents(authority, windows=False)
        reasons = [f"missing AGENTS provenance field: {key}" for key, ok in checks.items() if not ok]
        if text != expected:
            reasons.append("generated AGENTS mirror payload no longer matches the current authority render")
        return {"status": "WARN" if reasons else "PASS", "exists": True, "checks": checks, "reasons": reasons}
    if path.name == "hooks.json":
        expected = render_hooks(authority, windows=False)
        if expected is None:
            return {"status": "PASS", "exists": path.exists(), "checks": {"expected_generation": False}, "reasons": []}
        if not path.exists():
            return {"status": "WARN", "exists": False, "checks": {"expected_generation": True}, "reasons": ["generated hooks mirror is missing"]}
        text = read_text(path)
        reasons = [] if text == expected else ["generated hooks mirror payload no longer matches the current authority render"]
        return {
            "status": "WARN" if reasons else "PASS",
            "exists": True,
            "checks": {"expected_generation": True, "matches_render": not reasons},
            "reasons": reasons,
        }
    text = read_text(path)
    expected = expected_header(authority, authority_path, policy)
    lines = text.splitlines()[:12]
    checks = {
        "marker": expected["marker"] in text,
        "source_authority": any(line == f"# source_authority={expected['source_authority']}" for line in lines),
        "source_hash": any(line == f"# source_hash={expected['source_hash']}" for line in lines),
        "role": any(line == f"# role={expected['role']}" for line in lines),
        "read_by_renderer": any(line == "# read_by_renderer=false" for line in lines),
        "user_override_source": any(line == "# user_override_source=false" for line in lines),
        "optional_user_override": any(line == f"# optional_user_override={expected['optional_user_override']}" for line in lines),
    }
    if not path.exists():
        return {"status": "WARN", "exists": False, "checks": checks, "reasons": ["generated mirror is missing"]}
    reasons = [f"missing provenance field: {key}" for key, ok in checks.items() if not ok]
    status = "PASS" if not reasons else "BLOCKED" if path.name == "config.toml" else "WARN"
    return {"status": status, "exists": True, "checks": checks, "reasons": reasons}


def config_policy_findings(path: Path, policy: dict[str, Any], classification: str, authority: dict[str, Any]) -> dict[str, Any]:
    payload = load_toml(path)
    features = payload.get("features", {}) if isinstance(payload, dict) else {}
    blocked_flags = {
        str(item).strip()
        for item in policy.get("blocked_active_feature_flags", [])
        if str(item).strip()
    }
    blocked_flags.update(
        str(item).strip()
        for item in authority.get("hardcoding_definition", {}).get("feature_rules", {}).get("forbidden_feature_flags", [])
        if str(item).strip()
    )
    required_true = required_true_features(policy, authority)
    active_forbidden = sorted(str(feature) for feature, enabled in features.items() if enabled and str(feature) in blocked_flags)
    reasons: list[str] = []
    for feature in active_forbidden:
        if feature == "telepathy":
            reasons.append("active telepathy flag detected")
        elif feature == "workspace_dependencies":
            reasons.append("active unsupported workspace_dependencies feature flag detected")
        else:
            reasons.append(f"active forbidden feature flag detected: {feature}")
    blocked_values = policy.get("blocked_generated_config_values", {})
    if classification == "generated_mirror" and str(payload.get("approval_policy", "")).strip() in set(blocked_values.get("approval_policy", [])):
        reasons.append("generated config still contains approval_policy=never")
    if classification == "generated_mirror" and str(payload.get("sandbox_mode", "")).strip() in set(blocked_values.get("sandbox_mode", [])):
        reasons.append("generated config still contains sandbox_mode=danger-full-access")
    if classification == "generated_mirror":
        for feature in sorted(required_true):
            if features.get(feature) is not True:
                reasons.append(f"required active feature missing from linux generated config: {feature}")
    if classification == "optional_user_override_source":
        for feature in sorted(required_true):
            if features.get(feature) is False:
                reasons.append(f"user override attempted to disable required active feature: {feature}")
    reasons.extend(shell_zsh_fork_dependency_reasons(payload, policy))
    return {
        "status": "BLOCKED" if reasons else "PASS",
        "blocked_reasons": reasons,
        "features": features,
        "approval_policy": str(payload.get("approval_policy", "")),
        "sandbox_mode": str(payload.get("sandbox_mode", "")),
    }


def user_override_config_paths(authority: dict[str, Any]) -> list[Path]:
    paths = runtime_paths(authority)
    candidates = [paths["windows_user_override"]]
    existing = [path.resolve() for path in candidates if path.exists()]
    return sorted(set(existing), key=lambda item: str(item))


def evaluate_config_provenance(repo_root: str | Path | None = None) -> dict[str, Any]:
    authority = load_authority(repo_root)
    raw_authority_path = authority_path_for(repo_root)
    repo_authority_path = canonical_authority_path(authority, repo_root)
    active_worktree_root = Path(repo_root).expanduser().resolve() if repo_root else ROOT.resolve()
    canonical_root = canonical_repo_root(authority, repo_root)
    policy_path = canonical_root / "contracts" / "config_provenance_policy.json"
    policy = load_json(policy_path, default={}) if policy_path.exists() else load_policy(repo_root)
    if not policy.get("blocked_active_feature_flags"):
        policy["blocked_active_feature_flags"] = authority.get("hardcoding_definition", {}).get("feature_rules", {}).get("forbidden_feature_flags", [])
    policy.setdefault(
        "blocked_generated_config_values",
        {
            "approval_policy": ["never"],
            "sandbox_mode": ["danger-full-access"],
        },
    )
    paths = runtime_paths(authority)
    surface = authority.get("canonical_execution_surface", {}) if isinstance(authority.get("canonical_execution_surface"), dict) else {}
    windows_native = (
        str(authority.get("canonical_execution_host", "")).strip() == "windows-native"
        or str(surface.get("id", "")).strip() == "windows-native"
        or str(surface.get("expected_os", "")).strip().lower() == "windows"
    )
    override_source_paths = [str(item) for item in user_override_config_paths(authority)]
    mirrors = [] if windows_native else [paths["linux_config"], paths["linux_agents"], paths["linux_hooks"]]
    classified_paths = [*mirrors, paths["linux_user_override"], repo_authority_path, *windows_policy_paths(paths)]
    classifications = {str(path): classify_path(path, repo_authority_path, paths) for path in classified_paths}
    self_feed_reasons: list[str] = []
    if raw_authority_path.resolve() != repo_authority_path.resolve():
        self_feed_reasons.append(
            f"worktree attempted to use non-canonical authority source: {raw_authority_path}"
        )
    if not windows_native and str(paths["linux_config"]) in override_source_paths:
        self_feed_reasons.append("linux generated mirror is being used as an override source")
    allowed_override = str(policy.get("optional_user_override_source", str(paths["linux_user_override"])))
    if any(path != allowed_override for path in override_source_paths):
        self_feed_reasons.append(f"optional user override source drifted away from {allowed_override}")
    generated_headers = {str(path): header_status(path, authority, repo_authority_path, policy) for path in mirrors}
    active_config_targets = [paths["windows_config"], paths["windows_user_override"]] if windows_native else [paths["linux_config"], paths["linux_user_override"]]
    active_config_findings = {
        str(path): config_policy_findings(path, policy, classifications.get(str(path), classify_path(path, repo_authority_path, paths)), authority)
        for path in active_config_targets
    }
    windows_policy_surface = windows_policy_surface_report(paths, authority, expected_linux_hooks=None)
    blocked_reasons = list(self_feed_reasons)
    blocked_reasons.extend(reason for payload in active_config_findings.values() for reason in payload.get("blocked_reasons", []))
    blocked_reasons.extend(f"{path_text}: {reason}" for path_text, payload in generated_headers.items() if payload["status"] == "BLOCKED" for reason in payload.get("reasons", []))
    blocked_reasons.extend(
        str(item.get("reason", ""))
        for item in windows_policy_surface.get("findings", [])
        if str(item.get("status", "PASS")).strip() == "BLOCKED"
    )
    app_state_surface = {
        "status": "PASS" if WINDOWS_CODEX_HOME.exists() else "WARN",
        "path": str(WINDOWS_CODEX_HOME),
        "classification": "app_state_evidence_only",
        "exists": WINDOWS_CODEX_HOME.exists(),
        "reason": "" if WINDOWS_CODEX_HOME.exists() else "Windows Codex App state was not observed on this host.",
    }
    warnings = [app_state_surface["reason"]] if app_state_surface["status"] == "WARN" and app_state_surface["reason"] else []
    warnings.extend(
        str(item.get("reason", ""))
        for item in windows_policy_surface.get("findings", [])
        if str(item.get("status", "PASS")).strip() == "WARN"
    )
    status = collapse_status(["BLOCKED" if blocked_reasons else "", "WARN" if warnings else ""])
    return {
        "status": status,
        "gate_status": "BLOCKED" if blocked_reasons else "PASS",
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "authority_path": str(repo_authority_path),
        "raw_authority_probe_path": str(raw_authority_path),
        "authority_hash": authority_hash(repo_authority_path),
        "canonical_repo_root": str(canonical_root),
        "active_worktree_root": str(active_worktree_root),
        "policy_path": str(policy_path),
        "allowed_optional_user_override_source": str(paths["windows_user_override"]),
        "override_source_paths": override_source_paths,
        "generated_mirror_contract": {
            "status": "BLOCKED" if self_feed_reasons else "PASS",
            "self_feed_reasons": self_feed_reasons,
            "mirrors_are_outputs_only": True,
            "canonical_repo_root": str(canonical_root),
            "active_worktree_root": str(active_worktree_root),
        },
        "classifications": classifications,
        "generated_headers": generated_headers,
        "active_config_findings": active_config_findings,
        "windows_policy_surface_status": windows_policy_surface.get("status", "PASS"),
        "windows_policy_surface_findings": windows_policy_surface.get("findings", []),
        "known_generated_windows_policy_files_deleted": [],
        "unknown_windows_policy_files_blocking": windows_policy_surface.get("unknown_blocking", []),
        "unknown_windows_policy_files_observed": windows_policy_surface.get("unknown_observed", []),
        "app_state_surface": app_state_surface,
        "blocked_reasons": blocked_reasons,
        "warnings": warnings,
    }


def render_markdown(report: dict[str, Any]) -> str:
    status = str(report.get("status", report.get("gate_status", "WARN")))
    override_source = str(report.get("allowed_optional_user_override_source", "")).strip() or "(unknown)"
    override_sources = report.get("override_source_paths", [])
    if not isinstance(override_sources, list):
        override_sources = []
    lines = [
        "# Config Provenance",
        "",
        f"- Status: {status}",
        f"- Canonical repo root: {report.get('canonical_repo_root', '')}",
        f"- Active worktree root: {report.get('active_worktree_root', '')}",
        f"- Authority source path: {report.get('authority_path', '')}",
        f"- Allowed optional user override: {override_source}",
        f"- Override sources: {', '.join(str(item) for item in override_sources) or '(none)'}",
    ]
    if report.get("blocked_reasons"):
        lines.extend(["", "## Blocked Reasons"])
        lines.extend(f"- {item}" for item in report["blocked_reasons"])
    if report.get("warnings"):
        lines.extend(["", "## Warnings"])
        lines.extend(f"- {item}" for item in report["warnings"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Check Codex config provenance, generated mirror contract, and stale active flags.")
    parser.add_argument("--repo-root", default=str(ROOT))
    parser.add_argument("--output-file", default=str(DEFAULT_OUTPUT_PATH))
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    report = evaluate_config_provenance(args.repo_root)
    output_path = Path(args.output_file).expanduser().resolve()
    save_json(output_path, report)
    write_markdown(output_path.with_suffix(".md"), render_markdown(report))
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(render_markdown(report), end="")
    return status_exit_code(report["status"])


if __name__ == "__main__":
    raise SystemExit(main())
