#!/usr/bin/env bash
# GENERATED - DO NOT EDIT
# generated by Dev-Management
# authority file: /home/andy4917/Dev-Management/contracts/workspace_authority.json
# canonical remote execution surface: ssh-devmgmt-wsl (devmgmt-wsl)
# canonical agent binary: Linux-native Codex CLI on the remote login-shell PATH
# forbidden primary runtime: /mnt/c/Users/anise/.codex/bin/wsl/codex
# failure mode: exit 127 if the canonical SSH runtime or remote codex command is unavailable
set -euo pipefail

host_alias="devmgmt-wsl"
repo_root="/home/andy4917/Dev-Management"
remote_cmd=$(python3 - "$repo_root" "$@" <<'PY'
import shlex
import sys
repo_root = sys.argv[1]
remote_exec = "codex"
args = ' '.join(shlex.quote(arg) for arg in sys.argv[2:])
command = f"cd {shlex.quote(repo_root)} && exec {shlex.quote(remote_exec)}"
if args:
    command = f"{command} {args}"
print(command)
PY
)
if [ -z "$remote_cmd" ]; then
  printf 'Failed to construct remote Codex command\n' >&2
  exit 127
fi
exec ssh -o BatchMode=yes "$host_alias" "$remote_cmd"
